# Generated by Django 3.2.4 on 2021-07-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_photographer_cv'),
        ('ads', '0006_auto_20210724_1327'),
        ('criteria', '0002_result_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('answer', models.CharField(max_length=200)),
                ('actual_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
        ),
    ]
