# Generated by Django 3.2.4 on 2021-06-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
