# Generated by Django 3.2.4 on 2021-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_delete_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('name_of_photography_school', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
                ('experience_in_month_or_year', models.CharField(choices=[('1', 'Month'), ('2', 'Year')], max_length=1)),
                ('Type_of_Work', models.CharField(choices=[('FR', 'Freelance'), ('CP', 'Company')], max_length=2)),
            ],
        ),
    ]
