# Generated by Django 3.2.4 on 2021-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_photographerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerapplication',
            name='is_rejected',
            field=models.BooleanField(default=True),
        ),
    ]
