# Generated by Django 3.2.4 on 2021-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_photographerapplication_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
