# Generated by Django 3.2.4 on 2021-07-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_photographerapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerapplication',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
