# Generated by Django 3.2.4 on 2021-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='txt_ref',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
