# Generated by Django 3.2.4 on 2021-07-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_application_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='img',
            field=models.ImageField(default='thumb_photos.png', null=True, upload_to='ads'),
        ),
    ]
