# Generated by Django 3.2.4 on 2021-07-20 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='apply_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
