# Generated by Django 3.2.4 on 2021-07-21 12:48

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[ads.validators.file_size]),
        ),
    ]
