# Generated by Django 3.2.4 on 2021-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_application_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='thumbnail',
            field=models.ImageField(default='thumb_photos.png', null=True, upload_to='thumbnails/'),
        ),
    ]
