# Generated by Django 3.2.4 on 2021-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_application_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('H', 'Hold')], default='N', max_length=1),
        ),
    ]
