# Generated by Django 3.2.4 on 2021-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('H', 'Hold'), ('N', 'Not Decided')], default='N', max_length=1),
        ),
    ]
