# Generated by Django 3.2.4 on 2021-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Hold', 'Hold'), ('Not Decided', 'Not Decided')], default='Not Decided', max_length=40),
        ),
    ]
