# Generated by Django 3.2.4 on 2021-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_application_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='start_application',
            field=models.BooleanField(default=False),
        ),
    ]
