# Generated by Django 3.2.4 on 2021-08-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_application_start_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='start_application',
        ),
    ]
