# Generated by Django 3.2.4 on 2021-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_remove_application_start_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='start_application',
            field=models.BooleanField(default=False),
        ),
    ]
