# Generated by Django 3.2.4 on 2021-08-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210811_0747'),
        ('ads', '0013_ad_start_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recruter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recruter'),
        ),
    ]
