# Generated by Django 3.2.4 on 2021-08-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_application_recruter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='thumb_photos.png', null=True, upload_to='applpictures')),
                ('appli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.application')),
            ],
        ),
    ]
