# Generated by Django 3.2.4 on 2021-07-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_photographer_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='cv',
        ),
    ]
