# Generated by Django 3.2.4 on 2021-07-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210727_1334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('photographers', 'date', 'timeslot')},
        ),
    ]
