# Generated by Django 3.2.4 on 2021-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_appointment_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='img',
            field=models.ImageField(default='thumb_photos.png', null=True, upload_to='pho'),
        ),
    ]
