# Generated by Django 3.2.4 on 2021-08-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_photographer_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographerwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.photographer')),
            ],
        ),
    ]
