# Generated by Django 3.2.4 on 2021-08-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_photographerwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='fold')),
                ('name', models.CharField(max_length=360)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.photographer')),
            ],
        ),
        migrations.AddField(
            model_name='photographerwork',
            name='fold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workfolder'),
        ),
    ]
