# Generated by Django 3.2.4 on 2021-08-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='request_service',
            field=models.CharField(choices=[('Photoshooting', 'Photoshooting'), ('videomaking', 'videomaking')], default='videomaking', max_length=255),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='thumb_photos.png', null=True, upload_to='potfolio')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
        ),
    ]
