# Generated by Django 3.2.4 on 2021-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210811_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='att_status',
            field=models.CharField(choices=[('attended', 'attended'), ('canceled', 'canceled'), ('Not attended', 'Not attended')], default='attended', max_length=255),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.photographer')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
        ),
    ]
