# Generated by Django 3.2.4 on 2021-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210811_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
