# Generated by Django 3.2.4 on 2021-08-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_feedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent'),
        ),
    ]
