# Generated by Django 3.2.4 on 2021-08-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210812_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruterapp',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
