# Generated by Django 3.2.4 on 2021-08-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_recruterapp_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruterapp',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
