# Generated by Django 3.2.4 on 2021-08-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_recruterapp_is_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruter',
            name='rec_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recruterapp'),
        ),
    ]
