# Generated by Django 3.2.4 on 2021-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210812_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='category',
            field=models.ManyToManyField(null=True, to='accounts.Category'),
        ),
    ]
