# Generated by Django 3.2.4 on 2021-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_talent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruterapp',
            name='tin_number',
        ),
        migrations.AddField(
            model_name='recruterapp',
            name='tin_numbr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
