# Generated by Django 3.2.4 on 2021-08-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210815_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruterapp',
            old_name='tin_numbr',
            new_name='tin_number',
        ),
    ]
