# Generated by Django 3.2.4 on 2021-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_tin_numbr_recruterapp_tin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='att_status',
            field=models.CharField(choices=[('attended', 'attended'), ('canceled', 'canceled'), ('Not attended', 'Not attended')], default='Not attended', max_length=255),
        ),
    ]
